jetty:
  context: '/myapp'
  connectors:
    # Jetty connector. If none is provided, Bootique creates a single HTTP connector on port 8080
    - port: 9999
  servlets:
     # override code settings for the servlet "servlet2"    
    servlet2:
      urlPatterns:
        - '/ss2'
      params:
        p3: v33
        p4: v44
  filters:
    # override filter "filter2" code settings     
    filter2:
      urlPatterns:
        - '/ss2/*'
