jetty:
  context: '/myapp'
  connectors:
    # Jetty connector. If none is provided, Bootique creates a single HTTP connector on port 9989
    - port: 9989
  staticResourceBase: "classpath:io/bootique/jetty/demo"
  servlets:
    first:
      params:
        # Note that "resourceBase" follows Bootique resource URL format
        # and hence can be a  "classpath:" URL or a filesystem path
        resourceBase: "classpath:io/bootique/jetty/demo"
        pathInfoOnly: true

    allowed:
      params:
        # Note that "resourceBase" follows Bootique resource URL format
        # and hence can be a  "classpath:" URL or a filesystem path
        resourceBase: "classpath:io/bootique/jetty/demo/ordinary"
        pathInfoOnly: true

    forbidden:
      params:
        # Note that "resourceBase" follows Bootique resource URL format
        # and hence can be a  "classpath:" URL or a filesystem path
        resourceBase: "classpath:io/bootique/jetty/demo/with_cors"
        pathInfoOnly: true

jettycors:
  urlPatterns:
    - "/with_cors/*"
  allowedOrigins: "*"
  allowedMethods: "GET,POST,PUT,OPTIONS,HEAD"
  allowedHeaders: "*"
