jetty:
  context: '/myapp'
  connectors:
    # Jetty connector. If none is provided, Bootique creates a single HTTP connector on port 9999
    - port: 9999
  staticResourceBase: "classpath:io/bootique/jetty/demo"
jettywebsocket:
  asyncSendTimeout: "5s"
  maxSessionIdleTimeout: "30min"
  maxBinaryMessageBufferSize: "30kb"
  maxTextMessageBufferSize: "45kb"