jetty:
  context: '/myapp'
  connectors:
    # Jetty connector. If none is provided, Bootique creates a single HTTP connector on port 8080
    - port: 9999
  staticResourceBase: "classpath:io/bootique/jetty/demo"
  servlets:
    servlet:
      params:
        # Note that "resourceBase" follows Bootique resource URL format
        # and hence can be a  "classpath:" URL or a filesystem path
        resourceBase: "classpath:io/bootique/jetty/demo"
        pathInfoOnly: true
jettywebsocket:
  asyncSendTimeout: "5s"
  maxSessionIdleTimeout: "30min"
  maxBinaryMessageBufferSize: "30kb"
  maxTextMessageBufferSize: "45kb"